package com.sayproject.model.Diet;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Diet {
	private int no;
	private String sample_id;
	private String food_code;
	private String food_name;
	private int year;
	private String food_classification;
	private String food_detailed_classification;
	private int serving_size;
	private String unit;
	private double total_content_g;
	private double total_content_ml;
	private double energy;
	private double water;
	private double protein;
	private double fat;
	private double carbohydrate;
	private double total_sugars;
	private double saccharose;
	private double glucose;
	private double fruit_sugar;
	private double lactose;
	private double maltose;
	private double dietary_fiber;
	private double calcium;
	private double iron_mg;
	private double iron_ug;
	private double magnesium;
	private double phosphorus;
	private double potassium;
	private double natrium;
	private double zinc;
	private double cuprum;
	private double manganese;
	private double selenium;
	private double retinol;
	private double betacarotene;
	private double vitamin_d3;
	private double tocopherol;
	private double tocotrienols;
	private double vitamin_b1;
	private double vitamin_b2;
	private double niacin;
	private double folicacid;
	private double vitamin_b12;
	private double vitamin_c;
	private double aminoacid;
	private double isoleucine;
	private double leucine;
	private double lysine;
	private double methionine;
	private double phenylalanine;
	private double threonine;
	private double valine;
	private double histidine;
	private double arginine;
	private double tyrosine;
	private double cysteine;
	private double alanine;
	private double aspartic_acid;
	private double glutamic_acid;
	private double glycine;
	private double proline;
	private double serine;
	private double cholesterol;
	private double total_saturated_fatty_acids;
	private double butyric_acid;
	private double caproic_acid;
	private double caprylic_acid;
	private double capric_acid;
	private double lauric_acid;
	private double myristic_acid;
	private double palmitic_acid;
	private double stearic_acid;
	private double arachidic_acid;
	private double myristoleic_acid;
	private double palmitoleic_acid;
	private double oleic_acid;
	private double bacsenic_acid;
	private double gadoleic_acid;
	private double linoleic_acid;
	private double alpha_linoleic_acid;
	private double gamma_linoleic_acid;
	private double eicosadienoic_acid;
	private double arachidonic_acid;
	private double eicosatrienoic_acid;
	private double eicosapentaenoic_acid;
	private double docosapentaenoic_acid;
	private double docosahexaenoic_acid;
	private double trans_fatty_acids;
	private double trans_oleic_acid;
	private double trans_linoleic_acid;
	private double trans_linolenic_acid;
	private double ash;
	private double caffeine;
}
